### ISSUE TITLE
View start time of activity

### ISSUE THREAD

**Issue by Scorpibear** [vitalliuss/lazycure#14]
As a user I want to see start time of all logged activities in order to review the day and edit in future.

**Comment by vitalliuss** [comment]
We can show start time in the following way:
18:21 playing chess 00:30
18:17 smoking 00:04
17:12 breakfast 01:05

**Comment by Scorpibear** [comment]
I wonder, does it make sense to present it in a grid, as Time Log window do in a desktop version? Please, vote

**Comment by vitalliuss** [comment]
I think it will be nice to have an additional "Time Log" view with full information:
strat time (hh:mm:ss), activity name, duration (hh:mm:ss), end time (hh:mm:ss)
17:15:34     reading     00:23:02     17:38:36
16:03:24     playing     01:12:10     17:15:34

the same format should be used in export activity.

And the main view can show start time. activity name and duration in short "hh:mm" format:
17:15 |    reading  -   00:23
16:03 |    playing   -  01:12

**Comment by Scorpibear** [comment]
Implemented as 17:15:34 reading 00:23:02 in table layout. Make sense to shorted after TimeLogView implementation, now leaving as with seconds is in order not to loose information.
