### ISSUE TITLE
Add fading scroll to the activities list

### ISSUE THREAD

**Issue by vitalliuss** [vitalliuss/lazycure#18]
Create a scroll with fading for easy access to old activities.

**Comment by Scorpibear** [comment]
Could you please specify details? I see that scrolling is working, what is
the reason for adding scroll and what "fading" mean?

**Comment by vitalliuss** [comment]
Well, fading scroll is a scroll when the list of elements is still moving after you finger left the touchscreen. When scrolling a long list (for example list of contact in phone book) it takes lot of time to move to the latest element. Fading scroll will increase the scrolling speed in this case. To feel the difference just compare the scrolling speed of phone book's contact list and lazycure's activities list.

**Comment by vitalliuss** [comment]
Scorpibear, please take a look - I've done some fade in d7005e5d5b7bcfb291be97f00a64a396733a45ca :)
