### ISSUE TITLE
Publish at Google Play

### ISSUE THREAD

**Issue by Scorpibear** [vitalliuss/lazycure#20]
Having it available at Google Play, simplifies it's update, help more people to reach it and provide feedback and possibly invites more developers.

People already try to find it there - http://www.facebook.com/mikhail.subach/posts/10151321744060348?comment_id=26743530&notif_t=feed_comment :)

**Comment by vitalliuss** [comment]
Done, the app is available here: https://play.google.com/store/apps/details?id=main.java.com.github.lazycure
