### ISSUE TITLE
Default activity

### ISSUE THREAD

**Issue by Scorpibear** [vitalliuss/lazycure#22]
As a user I want to have possibility to record activity with default name 'rest' when Done button is pressed and nothing is specified. This functionality should be optional, turned off by default, because the new users have to get habit to specify everything they are doing. This functionality useful for experienced time loggers and it saves time on timelogging itself.

**Comment by vitalliuss** [comment]
Done, the feature can be turned on in "Settings => Advanced => Default activity mode"
