### ISSUE TITLE
Separate activities created today by separation line

### ISSUE THREAD

**Issue by vitalliuss** [vitalliuss/lazycure#9]
As a user I want to see today's activities separated from yesterday's by the separation line:

 playing chess 00:30:17
 smoking 00:03:52
 breakfast 00:30:08
 ==================
 sleeping 07:02:49
 reading 00:27:03

**Comment by Scorpibear** [comment]
Possibly even more useful to specify date inside of separation line:
playing chess 00:30:17
smoking 00:03:52
breakfast 00:30:08
=====2012-06-13======
sleeping 07:02:49
reading 00:27:03

**Comment by vitalliuss** [comment]
Good idea, let's do this way.

**Comment by vitalliuss** [comment]
Done.
